# This is a basic workflow that is manually triggered

name: Conn Man Commit Scanner

on:
  workflow_dispatch:

jobs:
  filter_connman_logs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the full history (all commits)

      # Step 2: Run the script
      - name: Run ConnManCommitScanner script
        run: |
          chmod +x .github/actions/ConnManCommitScanner/ConnManCommitScanner.sh
          .github/actions/ConnManCommitScanner/ConnManCommitScanner.sh "./"

      # Step 3: Upload the filtered logs as an artifact
      - name: Upload filtered logs
        uses: actions/upload-artifact@v4
        with:
          name: filtered_connman_logs
          path: filtered_connman_logs.csv

      # Step 4: Upload the summary file as an artifact
      - name: Upload the commit summary file
        uses: actions/upload-artifact@v4
        with:
          name: commit_summary
          path: commit_summary.txt
