name: Conn Man Commit Scanner

on:
  # Manual Trigger
  workflow_dispatch:

jobs:
  filter_connman_logs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch the full history (all commits)

      # Step 2: Run the script
      - name: Run ConnManCommitScanner script
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          .github/actions/ConnManCommitScanner/ConnManCommitScanner.sh
          ls

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install slack-sdk

      # Step 5: Run the Python script
      - name: Upload file to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: python .github/actions/ConnManCommitScanner/slackUploader.py

      # Step 6: Prepare logs and summary for upload
      - name: Prepare artifact directory
        run: |
          mkdir -p connman_report  # Create a directory to hold the files
          mv connman_commits.csv connman_report/
          mv report_summary.txt connman_report/

      # Step 7: Upload the combined artifact (directory)
      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: connman_report
          path: connman_report
