# This is a basic workflow that is manually triggered

name: Conn Man Commit Scanner

on:
  workflow_dispatch:
    inputs:
      include_keyword:
        description: "Keyword or phrase to include in the commit message."
        required: true
        default: "by team_id"
      exclude_keyword:
        description: "Keyword or phrase to exclude from the commit message."
        required: false
        default: "cis2_example"

jobs:
  filter_logs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history (all commits)

      # Step 2: Run the script
      - name: Run ConnManCommitScanner script
        run: |
          chmod +x .github/actions/ConnManCommitScanner/entrypoint.sh
          .github/actions/ConnManCommitScanner/entrypoint.sh "./"
        env:
          INCLUDE_KEYWORD: ${{ inputs.include_keyword }}
          EXCLUDE_KEYWORD: ${{ inputs.exclude_keyword }}

      # Step 3: Upload the filtered logs as an artifact
      - name: Upload filtered logs
        uses: actions/upload-artifact@v3
        with:
          name: filtered_logs
          path: filtered_logs.csv
