# This is a basic workflow that is manually triggered

name: Conn Man Commit Scanner

on:
  # Manual Trigger
  workflow_dispatch:

  # Trigger automatically on a weekly schedule
  schedule:
    - cron: "0 0 * * 0"  # Every Sunday at 00:00 UTC

jobs:
  filter_connman_logs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the full history (all commits)

      # Step 2: Run the script
      - name: Run ConnManCommitScanner script
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          .github/actions/ConnManCommitScanner/ConnManCommitScanner.sh


      # Step 3: Prepare logs and summary for upload
      - name: Prepare artifact directory
        run: |
          mkdir -p connman_report  # Create a directory to hold the files
          mv connman_commits.csv connman_report/
          mv report_summary.txt connman_report/

      # Step 4: Upload the combined artifact (directory)
      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: connman_report
          path: connman_report

      # Step 5: Send message through slack
      - name: Send GitHub Action data to a Slack workflow
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload-file-path: "connman_report"
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger