# This is a basic workflow that is manually triggered

name: Conn Man Commit Scanner

on:
  workflow_dispatch:
    inputs:
      include_keyword:
        description: "Keyword or phrase to include in the commit message"
        required: true
        default: "by team_id"
      exclude_keyword:
        description: "Keyword or phrase to exclude from the commit message"
        required: false
        default: "cis2_example"

jobs:
  filter_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run log filter script script
        uses: ./.github/actions/ConnManCommitScanner # Path to your custom action
        with:
          args: "../../"
        env:
          INCLUDE_KEYWORD: "by team_id" # Set to your include keyword
          EXCLUDE_KEYWORD: "cis2_example" # Set to your exclude keyword

      - name: Upload filtered logs
        uses: actions/upload-artifact@v3
        with:
          name: filtered_logs
          path: filtered_logs.csv
