# This is a basic workflow that is manually triggered

name: Conn Man Commit Scanner

on:
  workflow_dispatch:

jobs:
  filter_connman_logs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the full history (all commits)

      # Step 2: Run the script
      - name: Run ConnManCommitScanner script
        run: |
          chmod +x .github/actions/ConnManCommitScanner/ConnManCommitScanner.sh
          .github/actions/ConnManCommitScanner/ConnManCommitScanner.sh "./"


      # Step 3: Prepare logs and summary for upload
      - name: Prepare artifact directory
        run: |
          mkdir -p connman_report  # Create a directory to hold the files
          mv connman_commits.csv connman_report/
          mv report_summary.txt connman_report/

      # Step 4: Upload the combined artifact (directory)
      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: connman_report
          path: connman_report